ALTER TABLE users ALTER COLUMN avatar_url TYPE VARCHAR(500);
ALTER TABLE handyman_profiles ALTER COLUMN avatar_url TYPE VARCHAR(500);
ALTER TABLE handyman_portfolio ALTER COLUMN image_url TYPE VARCHAR(500);
